os:
  - osx

language: node_js

node_js:
  - "node"

before_script: ./script/ci

sudo: false

install:
  - npm install

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
